ROSTemplateFormatVersion: '2015-09-01'
Resources:
  PAIService:
    Type: ALIYUN::PAI::Service
    Properties:
      ServiceConfig:
        containers:
          - image: eas-registry-vpc.cn-hangzhou.cr.aliyuncs.com/pai-eas/python-inference:3.6-ubuntu1804
            port: 8000
            script: python app.py
        metadata:
          instance: 1
          name: ros_test_pai
          cpu: 4
          memory: 8000
