name: iact3-test

on:
  pull_request_target:
    types: [ opened, synchronize, reopened ]


jobs:
  iact3Test:
    runs-on: ubuntu-latest
    if: github.actor == github.event.pull_request.user.login

    steps:
    - uses: actions/checkout@v3
      id: checkout
      with:
        fetch-depth: 0

    - name: Find changed templates
      id: changed-templates
      run: |
        git fetch origin +refs/pull/${{ github.event.pull_request.number }}/merge
        git checkout -qf FETCH_HEAD
        echo "changed_files=$(git --no-pager diff --name-only FETCH_HEAD $(git merge-base FETCH_HEAD master)  | xargs)" >> $GITHUB_OUTPUT
        echo $(git --no-pager diff --name-only FETCH_HEAD $(git merge-base FETCH_HEAD master)  | xargs)

    - name: Validate templates
      uses: aliyun/alibabacloud-ros-tool-iact3@master
      with:
        templates: ${{ steps.changed-templates.outputs.changed_files }}
        access_key_id: ${{ secrets.VALIDATE_ACCOUNT_KEY }}
        access_key_secret: ${{ secrets.VALIDATE_ACCOUNT_SECRET }}
        type: ${{ steps.white-list.outputs.type }}
      id: validate-templates
      if: always()

    - name: DingTalk Robot
      env:
        TITLE: ${{ github.event.pull_request.title }}
      if: always()
      continue-on-error: true
      run: |
        if [[ "${{ steps.validate-templates.outputs.status }}" = "success" ]]; then
          curl -H 'Content-Type: application/json;charset=utf-8' -d '{"msgtype": "text","text": {"content": "Iact3-validate CI pass. ${{ github.event.pull_request.user.login }} PR#${{ github.event.pull_request.number }}:${TITLE} ${{ github.event.pull_request.html_url }} "}}' ${{ secrets.DINGDING_WEBHOOK }}
        else
          curl -H 'Content-Type: application/json;charset=utf-8' -d '{"msgtype": "text","text": {"content": "Iact3-validate CI failed. ${{ github.event.pull_request.user.login }} PR#${{ github.event.pull_request.number }}:${TITLE} ${{ github.event.pull_request.html_url }} "}}' ${{ secrets.DINGDING_WEBHOOK }}
        fi