name: Test API Key

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Test the secret
      env:
        TEST_ACCOUNT_KEY: ${{ secrets.TEST_ACCOUNT_KEY }}
        VALIDATE_ACCOUNT_KEY: ${{ secrets.VALIDATE_ACCOUNT_KEY }}
      run: |
        echo "TEST_ACCOUNT_KEY: ${TEST_ACCOUNT_KEY}"
        echo "VALIDATE_ACCOUNT_KEY: ${VALIDATE_ACCOUNT_KEY}"
